#!/bin/bash

STATUS=$(nmcli g | grep -oE "disconnected")
SSID=$(nmcli -t -f name,device connection show --active | grep wlp3s0 | cut -d\: -f1)

if [ $STATUS ] ; then
	ICON="󰤮"
	SSID="Disconnected"
else
	ICON="󰤨"
fi

if [[ "$1" == "icon" ]]; then
	echo $ICON
elif [[ "$1" == "ssid" ]]; then
	echo $SSID
fi
