#!/bin/bash

# Use pacman or change it to a package manager of your choice (has to support pacman syntax like yay for instance)
pkgmgr=pacman

# Packages that have to be installed before running the setup script
required=(
	git
	gum
)

if ! command -v $pkgmgr &> /dev/null; then
	printf "[ ERROR ] Couldn't find a supported package manager ($pkgmgr). Exiting...\n"
	exit 1
fi

for pkg in "${required[@]}"; do
	if sudo $pkgmgr -Q "$pkg" &> /dev/null; then
		printf "[ Skipped ] $pkg is already installed...\n"
	else
		printf "=> Installing $pkg...\n"
		if sudo $pkgmgr -S --noconfirm "$pkg" &> /dev/null; then
			printf "[ Installed ] Successfully installed $pkg...\n"
		else
			printf "[ ERROR ] Failed to install $pkg!\n"
		fi
	fi
done

# Run a different script for setting up all config files
./setup
