#!/bin/bash

pkgmgr=pacman

# Helper functions

choose_multiple()
{
	gum choose --cursor-prefix="[ ] " --selected-prefix="[x] " --unselected-prefix="[ ] " --no-limit "$@"
}

choose_one()
{
	gum choose "$@"
}

install_pkgs()
{
	for pkg in "$@"; do
		if $pkgmgr -Q "$pkg" &> /dev/null; then
			echo "[ Skipped ] $pkg is already installed..."
		else
			gum spin --title="Installing $pkg..." -- $pkgmgr --noconfirm -S $pkg
			echo "=> Successfully installed $pkg..."
		fi
	done
}

install_helper()
{
	if command -v $1 &> /dev/null; then
		echo "[ Skipped ] $1 is already installed..."
		pkgmgr=$1
		return 0
	fi

	gum spin --title="Cloning repo..." -- git clone "https://aur.archlinux.org/$1.git"
	cd $1
	gum spin --title="Building... " -- makepkg --noconfirm -si
	cd ..
	rm -rf "./$1"

	if command -v $1 &> /dev/null; then
		echo "=> Successfully installed $1"
		pkgmgr=$1
	else
		echo "[ ERROR ] Failed to install $1..."
	fi
}

# Installation

clear

# Choosing an AUR helper

echo "Choose your AUR helper:"
OPTIONS=$(choose_one "Yay" "Paru")
case $OPTIONS in
	Yay)
		install_helper yay ;;
	Paru)
		install_helper paru ;;
esac

# Choosing a shell

echo
echo "Choose which shell you want to use (Zsh is recommended, Bash has no config apart from a prompt):"
OPTIONS=$(choose_one "Zsh" "Bash")
case $OPTIONS in
	Zsh)
		install_pkgs zsh
		if [[ "$SHELL" != "$(which zsh)" ]]; then
			chsh -s $(which zsh)
		else
			echo "[ Skipped ] $(which zsh) is already the default shell..."
		fi
		;;
	Bash)
		install_pkgs bash 
		if [[ "$SHELL" != "$(which bash)" ]]; then
			chsh -s $(which bash)
		else
			echo "[ Skipped ] $(which bash) is already the default shell..."
		fi
		;;
esac

# Installing packages

echo
echo "Choose which required packages to install:"
OPTIONS=$(choose_multiple --selected=* hyprland nvim kitty swww starship python-pywal16 python-pywalfox imagemagick slurp grim wl-clipboard less)
install_pkgs $OPTIONS

echo
echo "Choose which optional packages to install:"
OPTIONS=$(choose_multiple --selected=* btop firefox)
install_pkgs $OPTIONS

echo
echo "Choose what fonts you want to install:"
OPTIONS=$(choose_multiple --selected=* noto-fonts noto-fonts-extra noto-fonts-cjk noto-fonts-emoji)
install_pkgs $OPTIONS

# Syncing the configs

DEST=$HOME
echo
if (gum confirm "Do you want to use GNU Stow to manage your configs?"); then
	install_pkgs stow
	export GUM_FILE_FILE=0
	echo "Choose where you want to put the dotfiles folder:"
	DOT_PATH=$(gum file --directory --all /home)
	cd ..

	if [[ "$DOT_PATH" != "$(pwd)" ]]; then
		mv -i dotfiles/ $DOT_PATH
	fi

	echo "=> Successfully moved dotfiles to $DOT_PATH..."
	cd "$DOT_PATH/dotfiles"
	./syncdots
else
	mv -i ./* ./.* $DEST
	cd ..
	rm -rf dotfiles/
	echo "=> Successfully moved all configs into $HOME"
fi

echo
echo "=> Successfully finished the installation..."
if(gum confirm "Do you want to reboot?"); then
	reboot
fi
