#!/bin/sh

ICON_PATH='/usr/share/icons/dracula-icons/symbolic/status/'

down() {
pamixer -d 2
volume=$(pamixer --get-volume)
[$volume -gt 0 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i "$ICON_PATH"audio-volume-low-symbolic.svg -r 2593 -u low
}

up() {
pamixer -i 2
volume=$(pamixer --get-volume)
[ $volume -lt 100 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i "$ICON_PATH"audio-volume-high-symbolic.svg -r 2593 -u low
}

mute() {
muted="$(pamixer --get-mute)"
if $muted; then
  pamixer -u
  dunstify -a "VOLUME" "Umuted" -i "$ICON_PATH"audio-volume-high-symbolic.svg -r 2593 -u low
else 
  pamixer -m
  dunstify -a "VOLUME" "Muted" -i "$ICON_PATH"audio-volume-muted-symbolic.svg -r 2593 -u low
fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
